#!/usr/bin/env bash

. ./configuration.sh

docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY $DOCKER_USER/$CICD_TRIGGERING_REPONAME:$CICD_TRIGGERING_VERSION $MYIP_INFRASTRUCTURE_STACK_NAME $CICD_TRIGGERING_BRANCH
