#!/usr/bin/env bash

. ./bashfunctions
. ./configuration.sh

requireVariable DOCKER_USER
requireVariable CICD_TRIGGERING_REPONAME
requireVariable CICD_TRIGGERING_VERSION
requireVariable MYIP_INFRASTRUCTURE_STACK_NAME
requireVariable CICD_TRIGGERING_BRANCH

echo "docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY $DOCKER_USER/$CICD_TRIGGERING_REPONAME:$CICD_TRIGGERING_VERSION $MYIP_INFRASTRUCTURE_STACK_NAME $CICD_TRIGGERING_BRANCH"
docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY $DOCKER_USER/$CICD_TRIGGERING_REPONAME:$CICD_TRIGGERING_VERSION $MYIP_INFRASTRUCTURE_STACK_NAME $CICD_TRIGGERING_BRANCH
