version: 2
jobs:
  build:
    docker:
    - image: docker:19-git

    working_directory: ~/workdir

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install bash
        command: |
          set +o pipefail
          apk --no-cache update && apk --no-cache add bash
    - run:
        name: Verify configuration
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWD

          export CICD_TRIGGERING_REPONAME=$DOCKER_USER/cicdw-myip-infrastructure
          export CICD_TRIGGERING_VERSION=latest
          export CICD_TRIGGERING_BRANCH=master
          ./deploy.sh

  deploy:
    docker:
      - image: docker:19-git

    working_directory: ~/workdir

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install bash
          command: |
            set +o pipefail
            apk --no-cache update && apk --no-cache add bash
      - run:
          name: Deploy application images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWD
            ./deploy.sh

